baseurl = "https://listmail.naraiu.cc/"
languageCode = "en-us"
title = "listmail - Free and open source self-hosted newsletter, mailing list manager, and transactional mails"


[taxonomies]
  tag = "tags"
