baseurl = "https://app.stmails.cn/"
languageCode = "en-us"
title = "stmails - Free and open source self-hosted newsletter, mailing list manager, and transactional mails"


[taxonomies]
  tag = "tags"
