site_name: listmail / Documentation
theme:
  name: material
  # custom_dir: "mkdocs-material/material"
  logo: "images/favicon.png"
  favicon: "images/favicon.png"
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  search:
    language: 'zh'
  language: "zh"
  font:
    text: 'Inter'
    weights: 400
  direction: 'ltr'

  feature:
    tabs: true
  features:
    - navigation.indexes
    - navigation.sections
    - content.code.copy

  palette:
    - scheme: default
      primary: "white"
      accent: "green"
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: "black"
      accent: "green"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


site_dir: _out
docs_dir: content

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
extra:
  homepage: https://listmail.naraiu.cc
  alternate:
    - name: English
      link: /docs/en/
      lang: en
    - name: 中文
      link: /docs/zh/
      lang: zh
extra_css:
  - "static/style.css"

copyright: "CC BY-SA 4.0"

nav:
  - "Introduction": index.md
  - "Getting Started":
    - "Installation": installation.md
    - "Configuration": configuration.md
    - "Upgrade": upgrade.md
  - "Using listmail":
    - "Concepts": concepts.md
    - "Templating": templating.md
    - "Querying and segmenting subscribers": querying-and-segmentation.md
    - "Bounce processing": bounces.md
    - "Messengers": "messengers.md"
    - "Archives": "archives.md"
    - "Internationalization": "i18n.md"
    - "Integrating with external systems": external-integration.md
    - "User roles and permissions": roles-and-permissions.md
  - "API":
    - "Introduction": apis/apis.md
    - "SDKs and libs": apis/sdks.md
    - "Subscribers": apis/subscribers.md
    - "Lists": apis/lists.md
    - "Import": apis/import.md
    - "Campaigns": apis/campaigns.md
    - "Media": apis/media.md
    - "Templates": apis/templates.md
#    - "Transactional": apis/transactional.md
    - "Bounces": apis/bounces.md
#  - "Maintenance":
#    - "Performance": maintenance/performance.md
#  - "Contributions":
#    - "Developer setup": developer-setup.md
