site_name: stmails / Documentation
site_url: https://app.stmails.cn/docs
theme:
  name: material
  # custom_dir: "mkdocs-material/material"
  logo: "images/favicon.png"
  favicon: "images/favicon.png"
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  search:
    language: 'en'
  language: "en"
  font:
    text: 'Inter'
    weights: 400
  direction: 'ltr'
  feature:
    tabs: true
  features:
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - content.code.copy
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - scheme: default
      primary: "white"
      accent: "green"
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: "black"
      accent: "green"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


site_dir: _out
docs_dir: content

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
#extra:
#  alternate:
#    - name: English
#      link: /
#      lang: en
#    - name: 中文
#      link: /docs/zh/
#      lang: zh
extra_css:
  - "static/style.css"

#copyright: "CC BY-SA 4.0"

plugins:
  - search
  - i18n:
      docs_structure: folder
      default_language: zh
      languages:
        - locale: zh
          name: 中文
          build: true
          default: true
          site_name: stmails / 文档
          nav_translations:
            Introduction: "介绍"
            Getting Started: "开始"
            Installation: "安装"
            Configuration: "配置"
            Upgrade: "更新"
            Using stmails: "使用 stmails"
            Concepts: "概念"
            Templating: "模板化"
            Querying and segmenting subscribers: "对订阅者进行查询与分段"
            Bounce processing: "退信处理"
            Messengers: "信使"
            Archives: "存档"
            Internationalization: "国际化"
            Integrating with external systems: "与外部系统集成"
            User roles and permissions: "用户角色和权限"
            Subscribers: "订阅者"
            Lists: "列表"
            Import: "导入"
            Campaigns: "营销活动"
            Media: "媒体"
            Templates: "模板"
            Bounces: "退信"







        - locale: en
          name: English
          build: true

nav:
  - "Introduction": index.md
  - "Getting Started":
    - "Installation": installation.md
    - "Configuration": configuration.md
    - "Upgrade": upgrade.md
  - "Using stmails":
    - "Concepts": concepts.md
    - "Templating": templating.md
    - "Querying and segmenting subscribers": querying-and-segmentation.md
    - "Bounce processing": bounces.md
    - "Messengers": "messengers.md"
    - "Archives": "archives.md"
    - "Internationalization": "i18n.md"
    - "Integrating with external systems": external-integration.md
    - "User roles and permissions": roles-and-permissions.md
  - "API":
    - "Introduction": apis/apis.md
    - "SDKs and libs": apis/sdks.md
    - "Subscribers": apis/subscribers.md
    - "Lists": apis/lists.md
    - "Import": apis/import.md
    - "Campaigns": apis/campaigns.md
    - "Media": apis/media.md
    - "Templates": apis/templates.md
#    - "Transactional": apis/transactional.md
    - "Bounces": apis/bounces.md
#  - "Maintenance":
#    - "Performance": maintenance/performance.md
#  - "Contributions":
#    - "Developer setup": developer-setup.md
